# Generated by Django 2.2 on 2020-01-14 09:51

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(blank=True)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('linkedin', models.URLField(blank=True)),
                ('education', models.CharField(max_length=200)),
                ('degree', models.CharField(choices=[('1', "Bachelor's degree"), ('2', 'Associate degree'), ('3', "Master's degree"), ('4', 'Doctoral degree')], default='1', max_length=50)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('about', models.CharField(blank=True, max_length=300)),
                ('certificate', models.CharField(blank=True, max_length=300)),
                ('skills', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentor.Address')),
            ],
        ),
    ]
