# Generated by Django 2.2 on 2020-01-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_auto_20200115_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='title',
            field=models.CharField(default='This is a default title', max_length=100),
        ),
    ]
